import { OpenAI } from "openai";
import { NextRequest, NextResponse } from "next/server";

const NEXT_PUBLIC_OPENAI_API_KEY = process.env.NEXT_PUBLIC_OPENAI_API_KEY;

if (!NEXT_PUBLIC_OPENAI_API_KEY) {
  throw new Error("Missing OPENAI_API_KEY environment variable");
}

const openai = new OpenAI({
  apiKey: NEXT_PUBLIC_OPENAI_API_KEY,
});

const validateInput = (data: any) => {
  const requiredFields = [
    "listingType",
    "propertyAddress",
    "propertyType",
    "locationAmenities",
    "propertyDescription",
    "interiorFeatures",
    "exteriorFeatures",
  ];

  for (const field of requiredFields) {
    if (!data[field]) {
      throw new Error(`Missing required field: ${field}`);
    }
  }
};

const generateOptimizedBrochurePrompt = (data: any) => `
As an expert real estate copywriter with deep knowledge of local markets, create an exceptionally detailed and personalized property listing description for the following property:

Property Details:
- Listing Type: ${data.listingType}
- Full Address: ${data.propertyAddress}
- Property Type: ${data.propertyType}
- Location and Amenities: ${data.locationAmenities}
- Property Description: ${data.propertyDescription}
- Interior Features: ${data.interiorFeatures}
- Exterior Features: ${data.exteriorFeatures}

Your task is to craft an engaging, highly detailed, and personalized property listing that showcases this specific property's unique features and its location's benefits. Use the provided information to paint a vivid picture that will resonate with potential buyers.

Guidelines:
1. Thoroughly analyze the property's location, nearby amenities, and local attractions. Incorporate specific details about the neighborhood, highlighting what makes it special.
2. Dive deep into the property's features, emphasizing unique selling points and how they contribute to a desirable lifestyle.
3. Use sensory language to help potential buyers imagine themselves living in the property.
4. Tailor the tone and style to match the property type and likely target audience.
5. Include relevant local market insights if applicable (e.g., "in the highly sought-after [neighborhood name]").

Provide the enhanced brochure content in the following JSON format:

{
  "headline": "An attention-grabbing headline that incorporates a key feature or location benefit (max 12 words)",
  "tagline": "A compelling tagline that complements the headline and adds another layer of appeal (max 20 words)",
  "overview": "A detailed yet concise summary highlighting the property's most impressive features and its location benefits (3-4 sentences)",
  "locationHighlights": [
    "2-3 specific points about the property's location, nearby amenities, or community features (detailed bullet points)"
  ],
  "propertyFeatures": {
    "exterior": "A paragraph detailing the exterior features, architecture, and outdoor spaces (3-4 sentences)",
    "interior": "A paragraph describing the interior layout, key rooms, and standout features (4-5 sentences)",
    "uniqueSellingPoints": [
      "2-3 standout features or selling points that make this property special (detailed bullet points)"
    ]
  },
  "lifestyleDescription": "A paragraph painting a picture of the lifestyle this property offers, incorporating location benefits and property features (3-4 sentences)",
  "marketInsight": "A brief statement about the property's value proposition in the current local market (1-2 sentences)",
  "callToAction": "A compelling call-to-action encouraging potential buyers to take the next step, mentioning a key feature or benefit as motivation (1-2 sentences)"
}

Ensure each section is highly detailed and specific to this property and its location. The description should be vivid, factual, and optimized for marketing purposes while maintaining a professional tone. The output must be a valid JSON object that can be parsed directly.
`;

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    validateInput(data);

    const prompt = generateOptimizedBrochurePrompt(data);

    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [{ role: "system", content: prompt }],
    });

    let brochureContent = response.choices[0].message.content;

    if (!brochureContent) {
      throw new Error("No content generated by OpenAI");
    }

    brochureContent = brochureContent
      .replace(/^```json\s*/, "")
      .replace(/\s*```$/, "");

    let jsonResponse;
    try {
      jsonResponse = JSON.parse(brochureContent);
    } catch (parseError) {
      console.error("Error parsing JSON:", parseError);
      return NextResponse.json(
        { error: "Invalid JSON response from AI" },
        { status: 500 }
      );
    }

    return NextResponse.json(jsonResponse);
  } catch (error) {
    console.error("Error generating property brochure content:", error);
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Error generating property brochure content",
      },
      { status: 500 }
    );
  }
}
